# Generated by Django 5.1.6 on 2025-03-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_pacientes_telefone_dadospaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospaciente',
            name='colesterol_total',
            field=models.IntegerField(default=200),
        ),
    ]
