# Generated by Django 5.1.6 on 2025-03-08 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_opcao_refeicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcao',
            name='refeicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.refeicao'),
        ),
    ]
